name: Dev Release for Google Drive

on:
  push:
    branches:
      - development

jobs:
  build:
    name: Build and Release to GDrive
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: List files
        run: ls app/build/outputs/apk/release/

      - name: Find APK
        id: find_apk
        run: |
          APK_PATH=$(find ./app/build/outputs/apk/release -name "*.apk" -print -quit)
          echo "::set-output name=apk_path::$APK_PATH"

      - name: Upload APK to Google Drive
        uses: google-github-actions/upload-to-drive@v1
        with:
          credentials_json: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}
          file: ${{ steps.find_apk.outputs.apk_path }}
          name: popcons.apk
          folder_id: ${{ vars.GDRIVE_FOLDER_ID }}

      - name: Cleanup APK
        if: always()
        run: rm -f ${{ steps.find_apk.outputs.apk_path }}